### ISSUE TITLE
Wont compile on 14.04 or 16.04

### ISSUE THREAD

**Issue by EliteMobb79** [VeriumReserve/verium-oldrepo#14]
I have tried to compile the wallet on 14.04 and 16.04 and get the same error on both. 

Building LevelDB ...
make[1]: Entering directory '/root/verium/src/leveldb'
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/builder.cc -o db/builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/c.cc -o db/c.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/dbformat.cc -o db/dbformat.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/db_impl.cc -o db/db_impl.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/db_iter.cc -o db/db_iter.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/filename.cc -o db/filename.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/log_reader.cc -o db/log_reader.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/log_writer.cc -o db/log_writer.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/memtable.cc -o db/memtable.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/repair.cc -o db/repair.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/table_cache.cc -o db/table_cache.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/version_edit.cc -o db/version_edit.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/version_set.cc -o db/version_set.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c db/write_batch.cc -o db/write_batch.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/block_builder.cc -o table/block_builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/block.cc -o table/block.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/filter_block.cc -o table/filter_block.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/format.cc -o table/format.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/iterator.cc -o table/iterator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/merger.cc -o table/merger.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/table_builder.cc -o table/table_builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/table.cc -o table/table.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c table/two_level_iterator.cc -o table/two_level_iterator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/arena.cc -o util/arena.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/bloom.cc -o util/bloom.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/cache.cc -o util/cache.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/coding.cc -o util/coding.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/comparator.cc -o util/comparator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/crc32c.cc -o util/crc32c.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/env.cc -o util/env.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/env_posix.cc -o util/env_posix.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/env_win.cc -o util/env_win.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/filter_policy.cc -o util/filter_policy.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/hash.cc -o util/hash.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/histogram.cc -o util/histogram.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/logging.cc -o util/logging.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/options.cc -o util/options.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c util/status.cc -o util/status.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c port/port_posix.cc -o port/port_posix.o
rm -f libleveldb.a
ar -rs libleveldb.a db/builder.o db/c.o db/dbformat.o db/db_impl.o db/db_iter.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o table/block_builder.o table/block.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table_builder.o table/table.o table/two_level_iterator.o util/arena.o util/bloom.o util/cache.o util/coding.o util/comparator.o util/crc32c.o util/env.o util/env_posix.o util/env_win.o util/filter_policy.o util/hash.o util/histogram.o util/logging.o util/options.o util/status.o port/port_posix.o
ar: creating libleveldb.a
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -DNDEBUG        -c helpers/memenv/memenv.cc -o helpers/memenv/memenv.o
rm -f libmemenv.a
ar -rs libmemenv.a helpers/memenv/memenv.o
ar: creating libmemenv.a
make[1]: Leaving directory '/root/verium/src/leveldb'
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/verium/src -I/root/verium/src/obj -DUSE_IPV6=1 -DUSE_AVX2 -I/root/verium/src/leveldb/include -I/root/verium/src/leveldb/helpers -DUSE_ASM -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/txdb-leveldb.d -o obj/txdb-leveldb.o txdb-leveldb.cpp
g++ -c  -MMD -o obj/scrypt-arm.o scrypt-arm.S
g++ -c  -MMD -o obj/scrypt-x86.o scrypt-x86.S
g++ -c  -MMD -o obj/scrypt-x64.o scrypt-x64.S
g++ -c  -MMD -o obj/sha2-arm.o sha2-arm.S
g++ -c  -MMD -o obj/sha2-x86.o sha2-x86.S
g++ -c  -MMD -o obj/sha2-x64.o sha2-x64.S
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/verium/src -I/root/verium/src/obj -DUSE_IPV6=1 -DUSE_AVX2 -I/root/verium/src/leveldb/include -I/root/verium/src/leveldb/helpers -DUSE_ASM -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o veriumd obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/irc.o obj/keystore.o obj/miner.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/noui.o obj/scrypt.o obj/miniunz.o obj/txdb-leveldb.o obj/scrypt-arm.o obj/scrypt-x86.o obj/scrypt-x64.o obj/sha2-arm.o obj/sha2-x86.o obj/sha2-x64.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l curl -l minizip -Wl,-Bdynamic -l z -l dl -l pthread /root/verium/src/leveldb/libleveldb.a /root/verium/src/leveldb/libmemenv.a
obj/scrypt.o: In function `HMAC_SHA256_80_init_8way':
/root/verium/src/scrypt.cpp:335: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:338: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:343: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:345: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:350: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:335: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:338: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:343: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:345: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:350: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:335: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:338: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:343: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:345: undefined reference to `sha256_init_8way'
/root/verium/src/scrypt.cpp:350: undefined reference to `sha256_transform_8way'
obj/scrypt.o: In function `PBKDF2_SHA256_80_128_8way':
/root/verium/src/scrypt.cpp:363: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:388: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:391: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:363: undefined reference to `sha256_transform_8way'
obj/scrypt.o:/root/verium/src/scrypt.cpp:388: more undefined references to `sha256_transform_8way' follow
obj/scrypt.o: In function `scrypt_N_1_1_256_24way':
/root/verium/src/scrypt.cpp:591: undefined reference to `scrypt_core_6way'
/root/verium/src/scrypt.cpp:592: undefined reference to `scrypt_core_6way'
/root/verium/src/scrypt.cpp:593: undefined reference to `scrypt_core_6way'
/root/verium/src/scrypt.cpp:594: undefined reference to `scrypt_core_6way'
obj/scrypt.o: In function `PBKDF2_SHA256_128_32_8way':
/root/verium/src/scrypt.cpp:403: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:404: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:405: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:413: undefined reference to `sha256_transform_8way'
/root/verium/src/scrypt.cpp:403: undefined reference to `sha256_transform_8way'
obj/scrypt.o:/root/verium/src/scrypt.cpp:404: more undefined references to `sha256_transform_8way' follow
collect2: error: ld returned 1 exit status
makefile.unix:202: recipe for target 'veriumd' failed
make: *** [veriumd] Error 1
root@localhost:~/verium/src#

**Comment by effectsToCause** [comment]
What architecture are you building on? 64 or 32

**Comment by EliteMobb79** [comment]
64 on both

**Comment by effectsToCause** [comment]
Sorry small linker bug in 64bit AVX unix makefile, it's now fixed, can pull changes.  Note if your CPU has AVX2 support you may want to set that flag to 1 in makefile, but not necessary.
